# Change these first
owner: SangjunYou # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: SangjunYou's Blog
    url: https://sangjunyou.github.io
  - name: Google
    url: https://www.google.com
  - name: Wikipedia
    url: https://en.wikipedia.org
  - name: Hacker News
    url: https://news.ycombinator.com
  - name: Test Broken Site
    url: https://thissitedoesnotexist.koj.co

status-website:
  baseUrl: upptime
  name: Upptime
