
owner: SangjunYou
repo: upptime
sites:
  - name: SangjunYou's Blog
    url: https://sangjunyou.github.io

status-website:
  baseUrl: upptime
  name: SangjunYou
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
