owner: sj-you
repo: upptime
sites:
  - name: sj-you's Blog
    url: https://sj-you.github.io

status-website:
  baseUrl: upptime
  name: sj-you
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
