# Change these first
owner: SangjunYou # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: SangjunYou's Blog
    url: https://sangjunyou.github.io

status-website:
  baseUrl: upptime
  name: SangjunYou
